# Generated by Django 5.1.4 on 2025-01-05 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customer_user'),
    ]

    operations = [
    ]
