# Generated by Django 5.1.4 on 2025-01-05 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20250105_1545'),
    ]

    operations = [
    ]
